# Generated by Django 5.0.6 on 2024-06-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeInp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('about', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('skill1', models.CharField(max_length=200, null=True)),
                ('skill2', models.CharField(max_length=200, null=True)),
                ('skill3', models.CharField(max_length=200, null=True)),
                ('skill4', models.CharField(max_length=200, null=True)),
                ('skill5', models.CharField(max_length=200, null=True)),
                ('degree1', models.CharField(max_length=200, null=True)),
                ('college1', models.CharField(max_length=200, null=True)),
                ('year1', models.CharField(max_length=200, null=True)),
                ('degree2', models.CharField(max_length=200, null=True)),
                ('college2', models.CharField(max_length=200, null=True)),
                ('year2', models.CharField(max_length=200, null=True)),
                ('degree3', models.CharField(max_length=200, null=True)),
                ('college3', models.CharField(max_length=200, null=True)),
                ('year3', models.CharField(max_length=200, null=True)),
                ('lang1', models.CharField(max_length=200, null=True)),
                ('lang2', models.CharField(max_length=200, null=True)),
                ('lang3', models.CharField(max_length=200, null=True)),
                ('project1', models.CharField(max_length=200, null=True)),
                ('durat1', models.CharField(max_length=200, null=True)),
                ('desc1', models.CharField(max_length=200, null=True)),
                ('project2', models.CharField(max_length=200, null=True)),
                ('durat2', models.CharField(max_length=200, null=True)),
                ('desc2', models.CharField(max_length=200, null=True)),
                ('company1', models.CharField(max_length=200, null=True)),
                ('post1', models.CharField(max_length=200, null=True)),
                ('duration1', models.CharField(max_length=200, null=True)),
                ('lin11', models.CharField(max_length=200, null=True)),
                ('company2', models.CharField(max_length=200, null=True)),
                ('post2', models.CharField(max_length=200, null=True)),
                ('duration2', models.CharField(max_length=200, null=True)),
                ('lin21', models.CharField(max_length=200, null=True)),
                ('ach1', models.CharField(max_length=200, null=True)),
                ('ach2', models.CharField(max_length=200, null=True)),
                ('ach3', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
