# Generated by Django 5.0.6 on 2024-07-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_topic_remove_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='option_letter',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
    ]
