# Generated by Django 5.0.6 on 2024-07-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer_option_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option_letter',
            field=models.CharField(choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd')], max_length=1, null=True),
        ),
    ]
