# Generated by Django 5.0.6 on 2024-06-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_applicant_name_applicant_applicant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
