# Generated by Django 5.0.3 on 2024-06-27 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_candidate_resume_file_alter_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
