# Generated by Django 5.0.6 on 2024-06-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_jobinfo_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobinfo',
            options={'ordering': ['-posted_date']},
        ),
    ]
